### ISSUE TITLE
`Joi.number().integer().valid(4)` no longer says the value is an `integer` in OpenAPI

### ISSUE THREAD

**Issue by jandppw** [kenspirit/joi-to-json#50]
In version `4.0.1`, the schema

```javascript
const decimals = Joi.number().integer().valid(4).example(4)
```

returns 

```yaml
decimals:
  enum:
    - 4
  type: number
  example: 4
```

in OpenAPI, instead of

```yaml
decimals:
  enum:
    - 4
  type: integer
  example: 4
```

This is not breaking, given that indeed the valid value / enum value is an integer, yet `type: integer`, as in earlier versions, would be more expressive.
